CREATE TABLE posts
(
    id        INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title     VARCHAR NOT NULL,
    body      TEXT    NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE
)
