CREATE TABLE post
(
    id        INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title     VARCHAR(100) NOT NULL,
    body      TEXT    NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE
)
