name: CI

on: [pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    environment:
      name: ci
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: 5432
    services:
      db:
        image: postgres:18.1
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        distribution: ["temurin"]
        java-version: ["25"]
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "25"
          cache: "pnpm"

      - name: Install pnpm packages
        run: pnpm install --frozen-lockfile

      - name: Java version
        env:
          JAVA_VERSION: ${{ matrix.java-version }}
        run: echo $JAVA_VERSION

      - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java-version }}
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: create table on database
        run: ./gradlew flywayMigrate

      - name: execute jOOQ code generator
        run: ./gradlew jooqCodegen

      - name: execute OpenAPI code generator
        run: ./gradlew openApiGenerate

      - name: Check
        run: ./gradlew check
